## NOT FOUND
GET  localhost:9292

###

## GET ALL PRODUCTS
GET http://localhost:9292/products

###

## INSERT A PRODUCT
POST http://localhost:9292/products
Content-Type: application/json

{
  "name": "Galaxy",
  "price": 2800
}

###

## GET A SPECIFIED PRODUCT BY id
GET http://localhost:9292/products/1

###

## UPDATE A PRODUCT BY id
PUT http://localhost:9292/products/5
Content-Type: application/json

{
  "name": "cascata",
  "price": "1000"
}

###

## DELETE A PRODUCT BY id
DELETE http://localhost:9292/products/4