version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
    ports:
      - '80:7000'
  banco_de_dados_em_memoria:
    image: memcached:1.6.21
  mensageria:
    image: rabbitmq:latest